name: Pipline demo test - java maven

on:
  push:
    branches:
      - main    
    paths:
    - 'java-maven/EmployeeManagement/**'
    # tags:
    #   - "java-maven-em-v*.*.*"

jobs:
  call-build:
    uses: my-actions-mc-1/workflow-1/.github/workflows/pipeline-java-maven.yaml@main
    with:
      java-version: '17'