name: workflow-test

env:
  project-path: ""

on:
  workflow_dispatch:

jobs:
  custom-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Custom javascript action
        uses: ./hello-world-javascript-action
        id: hello
        with:
          who-to-greet: "Obi-Wan Kenobi"

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Get Pokemon info
        id: pokemon
        run: |
          response=$(curl -s https://pokeapi.co/api/v2/pokemon/pikachu)
          echo "api_response=$response" >> $GITHUB_OUTPUT

      - name: Display pokemon info
        run: echo ${{ steps.pokemon.outputs.api_response }} | jq -r '.abilities'
